### ISSUE TITLE
Alternate solutions?

### ISSUE THREAD

**Issue by drewkeat** [learn-co-curriculum/quote-maker-react-lab#45]
### Canvas Link

https://learning.flatironschool.com/courses/1883/assignments/125712?module_item_id=259672

### Concern

I've worked this lab for too long, and I can't get the tests to pass.  The application works as described in my browser and I have one test failing: 

```
1) QuoteCard (Revisited)
       calls upvoteQuote action creator and updates the quote's vote count in the Redux store:
     AssertionError: expected 1 to be one of [ 1000, '1000' ]
      at Context.<anonymous> (test/reducers/quotesReducerTests.js:162:52)
      at processImmediate (node:internal/timers:464:21)
```

The test language is inscrutable, so I'm led to believe that there is a specific syntactic issue on my part, but I cannot find it for the life of me.

Here's a link to my repo.
https://github.com/drewkeat/quote-maker-react-lab

I would love to understand what I'm missing, so please feel free to let me know.

### Additional Context

All app functionality performs as described in specs

### Suggested Changes

Provide room in testing for a map-based solution rather than needlessly slicing the array.

**Comment by graciemcguire** [comment]
Hey @drewkeat, thanks for raising this issue! 
It looks like on [line 4 in your reducer](https://github.com/drewkeat/quote-maker-react-lab/blob/master/src/reducers/quotes.js), you are hard coding the votes a count of 0.
<img width="834" alt="Screen Shot 2022-01-06 at 9 34 15 AM" src="https://user-images.githubusercontent.com/40892567/148417842-ac6f803d-172d-47c5-a869-e075f31eaa1e.png">

The tests are creating a quote using your `ADD_QUOTE` action *(line 152)*, and then simulates a click on the button to `upvote` afterwards on *line 160*.

<img width="1025" alt="Screen Shot 2022-01-06 at 9 48 38 AM" src="https://user-images.githubusercontent.com/40892567/148419067-55e65fd7-727d-4947-b005-009a337c023f.png">

Because you are reassigning the votes from `999` to `0` in your reducer the test won't pass, because it's looking for a vote count of `1000`. If you change line 4 in your reducer to `let quote = {...action.quote}`, the test should pass!

Hope this helps, and happy coding! 💙

**Comment by drewkeat** [comment]
Thank you so much!  That is a relief. I couldn’t get a clear answer and the app was functioning as expected. I knew it had to be something throwing the tests and that makes sense. Your detailed explanation is VERY appreciated. 

Sent from iPhone
--
